sound/gimrats/gimratfall1.wav
sound/gimrats/gimratfloet.wav
sound/gimrats/gimratpc.wav
sound/gimrats/gimratsanlag.wav
sound/gimrats/gimrattele2.wav
sound/gimrats/gimratweb.wav
sound/gimrats/gimratwecker.wav
maps/csde_gimlirats.txt
maps/csde_gimlirats.bsp