prodigy2k.wad
maps/de_prodigy2k.bsp
maps/de_prdigy2k.txt
gfx/env/prodigy2k_dn.tga
gfx/env/prodigy2k_up.tga
gfx/env/prodigy2k_ft.tga
gfx/env/prodigy2k_bk.tga
gfx/env/prodigy2k_rt.tga
gfx/env/prodigy2k_lf.tga
sound/de_prodigy2k/fallscream.wav
sound/de_prodigy2k/helicopter.wav
sound/de_prodigy2k/modemdial.wav
sound/de_prodigy2k/musicback.wav
sound/de_prodigy2k/radiomusic.wav
sound/de_prodigy2k/server.wav
sound/de_prodigy2k/wind.wav
sprites/glow01.spr
sprites/prodigy2k_glow.spr
sprites/xsmoke1.spr
